In [2]:
s = ['dog', 'cat', 'lion']
print(s)

['dog', 'cat', 'lion']


In [3]:
numberOfAnimals = ('dog', 4), ('cat', 7), ('lion', 69)
d, c, l = numberOfAnimals
print(d, c, l)

('dog', 4) ('cat', 7) ('lion', 69)


In [5]:
uniqueFinder = set('Banana')

In [6]:
print(uniqueFinder)

{'n', 'a', 'B'}


In [7]:
import numpy as np

In [8]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [11]:
y = np.array([[1, 4, 3], [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [12]:
y.shape

(2, 3)

In [13]:
y.size

6

In [15]:
z = np.arange(1, 2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999], shape=(1999,))

In [18]:
a = np.arange(0.5, 3, 0.5)
a

array([0.5, 1. , 1.5, 2. , 2.5])

In [3]:
import numpy as np


In [6]:
y = np.array([[1, 4, 3], [9, 2, 7]])
y[0, 1]

np.int64(4)

In [7]:
y[0, 1]

np.int64(4)

In [8]:
y[0]

array([1, 4, 3])

In [9]:
y[0, :]

array([1, 4, 3])

In [11]:
y[ :, -1]

array([3, 7])

In [ ]:
y[